# Generated by Django 3.1.2 on 2021-09-18 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='student',
            new_name='students',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='subject',
            new_name='subjects',
        ),
    ]
