# Generated by Django 3.1.2 on 2021-09-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20210907_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'STUDENT'), ('teacher', 'TEACHER'), ('admin', 'ADMIN')], max_length=10),
        ),
    ]
