# Generated by Django 3.1.2 on 2021-09-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20210915_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersubjectregistration',
            name='students',
            field=models.ManyToManyField(null=True, to='management.StudentCourseRegistration'),
        ),
    ]
