# Generated by Django 3.1.2 on 2021-09-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20210909_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
