# Generated by Django 3.1.2 on 2021-10-04 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20211004_1314'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailVerication',
            new_name='EmailVerification',
        ),
    ]
