# Generated by Django 3.1.2 on 2021-09-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_delete_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='course',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='teacher',
            field=models.CharField(max_length=200),
        ),
    ]
