# Generated by Django 3.1.2 on 2021-09-10 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20210910_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersubjectregistration',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.course'),
            preserve_default=False,
        ),
    ]
