# Generated by Django 3.1.2 on 2021-09-10 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_teachersubjectregistration_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersubjectregistration',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.subject'),
        ),
    ]
